base_url = "https://www.netflix.com/tudum/top10"

#MongoDB Credentioals
mongo_db_credentials = {
    'ip':'10.110.39.56',
    'port':'27017',
    'username':'root',
    'password':'example'
}

date_str_format = "%Y-%m-%d"

web_page_dispaly_date_format = '%m/%d/%y'

global_lists_url_additions = {
    'english_movie':'',
    'english_tv':'tv',
    'non_english_movie':'films-non-english',
    'non_english_tv':'tv-non-english'
}
country_lists_url_additions = {
    'movie':'',
    'tv':'tv'
}
countries = {'Argentina': 'argentina',
 'Australia': 'australia',
 'Austria': 'austria',
 'Bahamas': 'bahamas',
 'Bahrain': 'bahrain',
 'Bangladesh': 'bangladesh',
 'Belgium': 'belgium',
 'Bolivia': 'bolivia',
 'Brazil': 'brazil',
 'Bulgaria': 'bulgaria',
 'Canada': 'canada',
 'Chile': 'chile',
 'Colombia': 'colombia',
 'Costa Rica': 'costa-rica',
 'Croatia': 'croatia',
 'Cyprus': 'cyprus',
 'Czech Republic': 'czechia',
 'Denmark': 'denmark',
 'Dominican Republic': 'dominican-republic',
 'Ecuador': 'ecuador',
 'Egypt': 'egypt',
 'El Salvador': 'el-salvador',
 'Estonia': 'estonia',
 'Finland': 'finland',
 'France': 'france',
 'Germany': 'germany',
 'Greece': 'greece',
 'Guadeloupe': 'guadeloupe',
 'Guatemala': 'guatemala',
 'Honduras': 'honduras',
 'Hong Kong': 'hong-kong',
 'Hungary': 'hungary',
 'Iceland': 'iceland',
 'India': 'india',
 'Indonesia': 'indonesia',
 'Ireland': 'ireland',
 'Israel': 'israel',
 'Italy': 'italy',
 'Jamaica': 'jamaica',
 'Japan': 'japan',
 'Jordan': 'jordan',
 'Kenya': 'kenya',
 'Kuwait': 'kuwait',
 'Latvia': 'latvia',
 'Lebanon': 'lebanon',
 'Lithuania': 'lithuania',
 'Luxembourg': 'luxembourg',
 'Malaysia': 'malaysia',
 'Maldives': 'maldives',
 'Malta': 'malta',
 'Martinique': 'martinique',
 'Mauritius': 'mauritius',
 'Mexico': 'mexico',
 'Morocco': 'morocco',
 'Netherlands': 'netherlands',
 'New Caledonia': 'new-caledonia',
 'New Zealand': 'new-zealand',
 'Nicaragua': 'nicaragua',
 'Nigeria': 'nigeria',
 'Norway': 'norway',
 'Oman': 'oman',
 'Pakistan': 'pakistan',
 'Panama': 'panama',
 'Paraguay': 'paraguay',
 'Peru': 'peru',
 'Philippines': 'philippines',
 'Poland': 'poland',
 'Portugal': 'portugal',
 'Qatar': 'qatar',
 'Romania': 'romania',
 'Reunion': 'reunion',
 'Saudi Arabia': 'saudi-arabia',
 'Serbia': 'serbia',
 'Singapore': 'singapore',
 'Slovakia': 'slovakia',
 'Slovenia': 'slovenia',
 'South Africa': 'south-africa',
 'South Korea': 'south-korea',
 'Spain': 'spain',
 'Sri Lanka': 'sri-lanka',
 'Sweden': 'sweden',
 'Switzerland': 'switzerland',
 'Taiwan': 'taiwan',
 'Thailand': 'thailand',
 'Trinidad and Tobago': 'trinidad-and-tobago',
 'Turkey': 'turkiye',
 'Ukraine': 'ukraine',
 'United Arab Emirates': 'united-arab-emirates',
 'United Kingdom': 'united-kingdom',
 'United States': 'united-states',
 'Uruguay': 'uruguay',
 'Venezuela': 'venezuela',
 'Vietnam': 'vietnam'}